#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  1 23:09:35 2019

@author: beverlyfu
"""
gift1 = input("What is one thing you would like for Christmas? ")
gift2 = input("What is another thing you would like for Christmas? ")
gift3 = input("What is the third thing you would like for Christmas? ")
gift_total = gift1+" "+ gift2 +" "+ gift3
print("These are the three things you will be getting this year: " + gift_total)
