#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  1 23:25:36 2019

@author: beverlyfu

"""

#two people split the bill
meal_cost = int(input("How much did the meal cost? "))
meal_and_tip = meal_cost*1.15
each_pays = meal_and_tip / 2
print("If 2 people are eating, and you decide to give a 15% tip, and go dutch...")
import time
time.sleep(1)
print("Each person should pay ",each_pays,"pounds for the meal.")

#more people split the bill
no_of_people = int(input("How many people ate? "))
meal_cost_b = int(input("How much did the meal cost? "))
percentage_tip = int(input("How much do you want to tip the waiter (in percentage)? "))
meal_and_tip_b = meal_cost_b * (1+percentage_tip/100)
each_pays_b = meal_and_tip_b / no_of_people
time.sleep(1)
print("Each person should pay ", each_pays_b, "pounds for the meal.")

#they go home in a taxi
dist_travelled = int(input("Please enter the distance the taxi must travel in miles: "))
cost_of_transport = dist_travelled * 0.45
time.sleep(1)
print("Including transport costs, each person must now pay ", ((cost_of_transport/no_of_people)+each_pays_b), "for transport in addition to the meal.")
