#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  1 23:14:33 2019

@author: beverlyfu
"""
shares = int(input("How many people will you be sharing the cash with? "))
money_each_gets = 1000/(shares+1)
print("Each person will get " , money_each_gets , "pounds")

